type FallbackProduct = {
  id: string;
  name: string;
  category: string;
  price: number;
  oldPrice?: number;
  stock: number;
  reorderLevel: number;
  rating: number;
  ratingCount: number;
  description: string;
  specs: Record<string, string>;
  image: string;
  featured?: boolean;
  trending?: boolean;
  bestSeller?: boolean;
  specialOffer?: boolean;
};

type FallbackOrderItem = {
  productId: string;
  name: string;
  price: number;
  quantity: number;
  image: string;
};

type FallbackOrder = {
  orderId: string;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  address: string;
  city: string;
  pincode: string;
  paymentMethod: 'Cash on Delivery' | 'Credit / Debit Card' | 'UPI / Wallet';
  items: FallbackOrderItem[];
  totalAmount: number;
  orderDate: string;
  status: 'Placed' | 'Confirmed' | 'Shipped' | 'Delivered';
};

const today = new Date();
function daysAgo(days: number): string {
  const date = new Date(today);
  date.setDate(date.getDate() - days);
  return date.toISOString();
}

export const fallbackProducts: FallbackProduct[] = [
  {
    id: 'p1',
    name: 'Aurora Wireless Over-Ear Headphones',
    category: 'Electronics',
    price: 2499,
    oldPrice: 3999,
    stock: 24,
    reorderLevel: 10,
    rating: 4.6,
    ratingCount: 1284,
    description: 'Immersive sound with active noise cancellation, 40-hour battery life, and plush memory-foam ear cushions for all-day comfort.',
    specs: { Battery: '40 hours', Connectivity: 'Bluetooth 5.3', Weight: '250g', Warranty: '1 year' },
    image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    featured: true,
    trending: true,
    bestSeller: true,
    specialOffer: true,
  },
  {
    id: 'p2',
    name: 'Pulse True Wireless Earbuds',
    category: 'Electronics',
    price: 1499,
    oldPrice: 2299,
    stock: 8,
    reorderLevel: 12,
    rating: 4.3,
    ratingCount: 942,
    description: 'Compact earbuds with punchy bass, touch controls, IPX5 water resistance, and a pocketable charging case.',
    specs: { Battery: '24 hours with case', Connectivity: 'Bluetooth 5.2', 'Water resistance': 'IPX5', Warranty: '6 months' },
    image: 'https://images.pexels.com/photos/33797659/pexels-photo-33797659.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    trending: true,
    bestSeller: true,
  },
  {
    id: 'p3',
    name: 'Vital Fit Smartwatch',
    category: 'Electronics',
    price: 3299,
    stock: 15,
    reorderLevel: 8,
    rating: 4.4,
    ratingCount: 610,
    image: 'https://images.pexels.com/photos/18662969/pexels-photo-18662969.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Track heart rate, SpO2, sleep, and 50+ sport modes. 1.8" AMOLED display with 7-day battery life.',
    specs: { Display: '1.8" AMOLED', Battery: '7 days', 'Water resistance': '5ATM', Sensors: 'HR, SpO2, Accelerometer' },
    featured: true,
    trending: true,
  },
  {
    id: 'p4',
    name: 'TrailCam 4K Action Camera',
    category: 'Electronics',
    price: 8999,
    oldPrice: 10999,
    stock: 6,
    reorderLevel: 5,
    rating: 4.7,
    ratingCount: 318,
    image: 'https://images.pexels.com/photos/4817132/pexels-photo-4817132.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: '4K60 action camera with electronic stabilization, waterproof body, and dual displays for vlogging.',
    specs: { Video: '4K @ 60fps', Stabilization: '6-axis EIS', Waterproof: '10m', Storage: 'microSD up to 256GB' },
    specialOffer: true,
  },
  {
    id: 'p5',
    name: 'Nimbus 14 Ultrabook Laptop',
    category: 'Electronics',
    price: 54999,
    stock: 12,
    reorderLevel: 4,
    rating: 4.8,
    ratingCount: 204,
    image: 'https://images.pexels.com/photos/8533587/pexels-photo-8533587.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: '14-inch ultrabook with 16GB RAM, 512GB SSD, and an all-day battery in a 1.2kg aluminum chassis.',
    specs: { CPU: 'Octa-core 2.4GHz', RAM: '16GB', Storage: '512GB SSD', Display: '14" 2.8K IPS', Weight: '1.2kg' },
    featured: true,
    bestSeller: true,
  },
  {
    id: 'p6',
    name: 'Slate 10 Tablet',
    category: 'Electronics',
    price: 18999,
    oldPrice: 21999,
    stock: 9,
    reorderLevel: 6,
    rating: 4.2,
    ratingCount: 388,
    image: 'https://images.pexels.com/photos/25809238/pexels-photo-25809238.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: '10.4" tablet with stylus support, quad speakers, and 12-hour battery for work and entertainment.',
    specs: { Display: '10.4" 2K', RAM: '6GB', Storage: '128GB', Battery: '12 hours' },
    specialOffer: true,
  },
  {
    id: 'p7',
    name: 'Boom 20 Portable Bluetooth Speaker',
    category: 'Electronics',
    price: 1799,
    stock: 30,
    reorderLevel: 10,
    rating: 4.5,
    ratingCount: 1521,
    image: 'https://images.pexels.com/photos/4917455/pexels-photo-4917455.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Room-filling 20W sound with deep bass, IPX7 waterproofing, and 18 hours of playtime.',
    specs: { Power: '20W', Battery: '18 hours', 'Water resistance': 'IPX7', Connectivity: 'Bluetooth 5.1' },
    trending: true,
    bestSeller: true,
  },
  {
    id: 'p8',
    name: 'ChargeUp 20000mAh Power Bank',
    category: 'Electronics',
    price: 1299,
    oldPrice: 1799,
    stock: 40,
    reorderLevel: 15,
    rating: 4.4,
    ratingCount: 2310,
    image: 'https://images.pexels.com/photos/4072683/pexels-photo-4072683.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: '20,000mAh dual-output power bank with 22.5W fast charging and a digital battery indicator.',
    specs: { Capacity: '20000mAh', Output: '22.5W PD', Ports: 'USB-C, USB-A x2', Weight: '350g' },
    bestSeller: true,
    specialOffer: true,
  },
  {
    id: 'p9',
    name: 'Glide Wireless Mouse',
    category: 'Electronics',
    price: 699,
    oldPrice: 999,
    stock: 8,
    reorderLevel: 10,
    rating: 4.1,
    ratingCount: 760,
    image: 'https://images.pexels.com/photos/7151696/pexels-photo-7151696.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Silent-click wireless mouse with ergonomic shape, 1600 DPI, and up to 18 months of battery.',
    specs: { DPI: '1600', Connectivity: '2.4GHz + Bluetooth', Battery: '18 months', Buttons: '5' },
    trending: true,
  },
  {
    id: 'p10',
    name: 'Tactile 75 Mechanical Keyboard',
    category: 'Electronics',
    price: 3299,
    stock: 18,
    reorderLevel: 8,
    rating: 4.6,
    ratingCount: 412,
    image: 'https://images.pexels.com/photos/9020272/pexels-photo-9020272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Hot-swappable 75% mechanical keyboard with RGB backlight, gasket mount, and PBT keycaps.',
    specs: { Layout: '75%', Switches: 'Hot-swappable', Keycaps: 'PBT', Backlight: 'RGB' },
    featured: true,
  },
  {
    id: 'p11',
    name: 'Stride Runner Sneakers',
    category: 'Fashion',
    price: 2199,
    oldPrice: 2999,
    stock: 22,
    reorderLevel: 10,
    rating: 4.4,
    ratingCount: 880,
    image: 'https://images.pexels.com/photos/1027130/pexels-photo-1027130.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Lightweight running sneakers with breathable knit upper and responsive cushioned midsole.',
    specs: { Upper: 'Engineered knit', Sole: 'EVA cushion', Weight: '260g', Sizes: 'UK 6-11' },
    trending: true,
    bestSeller: true,
    specialOffer: true,
  },
  {
    id: 'p12',
    name: 'Classic Denim Jacket',
    category: 'Fashion',
    price: 1799,
    stock: 14,
    reorderLevel: 8,
    rating: 4.3,
    ratingCount: 540,
    image: 'https://images.pexels.com/photos/6770037/pexels-photo-6770037.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Timeless mid-wash denim jacket with a relaxed fit and durable button-front closure.',
    specs: { Material: '100% cotton denim', Fit: 'Relaxed', Care: 'Machine wash cold', Sizes: 'S-XXL' },
    featured: true,
  },
  {
    id: 'p13',
    name: 'Cozy Knit Sweater',
    category: 'Fashion',
    price: 1299,
    oldPrice: 1999,
    stock: 7,
    reorderLevel: 10,
    rating: 4.5,
    ratingCount: 392,
    image: 'https://images.pexels.com/photos/14642651/pexels-photo-14642651.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Soft ribbed-knit sweater with a crew neckline, perfect for layering through the seasons.',
    specs: { Material: 'Acrylic blend', Fit: 'Regular', Care: 'Hand wash', Sizes: 'S-XXL' },
    specialOffer: true,
  },
  {
    id: 'p14',
    name: 'Aviator Polarized Sunglasses',
    category: 'Accessories',
    price: 899,
    oldPrice: 1499,
    stock: 35,
    reorderLevel: 12,
    rating: 4.2,
    ratingCount: 1102,
    image: 'https://images.pexels.com/photos/8989491/pexels-photo-8989491.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Classic aviator sunglasses with polarized lenses, UV400 protection, and a lightweight metal frame.',
    specs: { Lens: 'Polarized', 'UV protection': 'UV400', Frame: 'Metal', Includes: 'Case + cloth' },
    trending: true,
    bestSeller: true,
    specialOffer: true,
  },
  {
    id: 'p15',
    name: 'Heritage Leather Belt',
    category: 'Accessories',
    price: 799,
    stock: 28,
    reorderLevel: 10,
    rating: 4.4,
    ratingCount: 318,
    image: 'https://images.pexels.com/photos/31959214/pexels-photo-31959214.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Full-grain leather belt with a brushed alloy buckle that ages beautifully over time.',
    specs: { Material: 'Full-grain leather', Width: '35mm', Buckle: 'Alloy', Sizes: 'S-XL' },
  },
  {
    id: 'p16',
    name: 'Trek Waterproof Hiking Boots',
    category: 'Fashion',
    price: 3499,
    oldPrice: 4499,
    stock: 11,
    reorderLevel: 8,
    rating: 4.6,
    ratingCount: 274,
    image: 'https://images.pexels.com/photos/31126065/pexels-photo-31126065.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Durable hiking boots with waterproof membrane, grippy outsole, and ankle support for the trails.',
    specs: { Upper: 'Synthetic + mesh', Sole: 'Rubber grip', Waterproof: 'Yes', Sizes: 'UK 6-12' },
    featured: true,
    specialOffer: true,
  },
  {
    id: 'p17',
    name: 'Amber Scented Candle Set',
    category: 'Home',
    price: 699,
    oldPrice: 999,
    stock: 42,
    reorderLevel: 15,
    rating: 4.7,
    ratingCount: 642,
    image: 'https://images.pexels.com/photos/13395697/pexels-photo-13395697.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Set of 3 soy-wax candles with amber, sandalwood, and vanilla notes for up to 30 hours each.',
    specs: { Wax: 'Soy', Burn: '30 hours each', Set: '3 candles', Weight: '200g each' },
    bestSeller: true,
    specialOffer: true,
  },
  {
    id: 'p18',
    name: 'Luna Ceramic Vase',
    category: 'Home',
    price: 1199,
    stock: 16,
    reorderLevel: 6,
    rating: 4.5,
    ratingCount: 210,
    image: 'https://images.pexels.com/photos/33126633/pexels-photo-33126633.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Hand-glazed ceramic vase with a matte finish, ideal for dried stems or fresh blooms.',
    specs: { Material: 'Ceramic', Height: '24cm', Finish: 'Matte glaze', Color: 'Off-white' },
    featured: true,
  },
  {
    id: 'p19',
    name: 'Cloudweave Throw Blanket',
    category: 'Home',
    price: 1599,
    oldPrice: 2199,
    stock: 19,
    reorderLevel: 8,
    rating: 4.6,
    ratingCount: 488,
    image: 'https://images.pexels.com/photos/31658575/pexels-photo-31658575.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Ultra-soft throw blanket with a chunky woven texture, perfect for cozy evenings.',
    specs: { Material: 'Polyester fleece', Size: '130x170cm', Care: 'Machine washable', Weight: '900g' },
    trending: true,
    specialOffer: true,
  },
  {
    id: 'p20',
    name: 'Brew Drip Coffee Maker',
    category: 'Home',
    price: 4299,
    stock: 13,
    reorderLevel: 6,
    rating: 4.4,
    ratingCount: 356,
    image: 'https://images.pexels.com/photos/12090814/pexels-photo-12090814.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: '12-cup drip coffee maker with programmable timer, anti-drip valve, and a thermal carafe.',
    specs: { Capacity: '12 cups', Carafe: 'Thermal', Power: '900W', Programmable: 'Yes' },
    bestSeller: true,
  },
  {
    id: 'p21',
    name: 'Halo LED Desk Lamp',
    category: 'Home',
    price: 1499,
    oldPrice: 1999,
    stock: 26,
    reorderLevel: 10,
    rating: 4.5,
    ratingCount: 720,
    image: 'https://images.pexels.com/photos/28461166/pexels-photo-28461166.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Adjustable LED desk lamp with 5 color temperatures, 10 brightness levels, and a USB charging port.',
    specs: { Power: '10W', 'Color temps': '2700K-6500K', Brightness: '10 levels', USB: '1 port' },
    trending: true,
    specialOffer: true,
  },
  {
    id: 'p22',
    name: 'Forest Wooden Cutlery Set',
    category: 'Home',
    price: 999,
    stock: 31,
    reorderLevel: 12,
    rating: 4.3,
    ratingCount: 264,
    image: 'https://images.pexels.com/photos/10707390/pexels-photo-10707390.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: '6-piece solid-wood utensil set with a holder, finished with food-safe oil.',
    specs: { Pieces: '6', Material: 'Rubberwood', Includes: 'Holder', Care: 'Hand wash' },
  },
  {
    id: 'p23',
    name: 'The Modern Mind (Hardcover)',
    category: 'Books',
    price: 549,
    oldPrice: 799,
    stock: 50,
    reorderLevel: 15,
    rating: 4.8,
    ratingCount: 1320,
    image: 'https://images.pexels.com/photos/433333/pexels-photo-433333.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'A bestselling exploration of focus, habit, and decision-making in a distracted age.',
    specs: { Pages: '320', Format: 'Hardcover', Language: 'English', Publisher: 'ShopSense Press' },
    bestSeller: true,
    specialOffer: true,
  },
  {
    id: 'p24',
    name: 'Voyage Leather Backpack',
    category: 'Accessories',
    price: 2799,
    oldPrice: 3999,
    stock: 17,
    reorderLevel: 8,
    rating: 4.6,
    ratingCount: 530,
    image: 'https://images.pexels.com/photos/14039946/pexels-photo-14039946.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Water-resistant leather backpack with a padded 15.6" laptop sleeve and anti-theft back pocket.',
    specs: { Material: 'PU leather', 'Laptop fit': '15.6"', Compartments: '4', Water: 'Resistant' },
    featured: true,
    trending: true,
    specialOffer: true,
  },
  {
    id: 'p25',
    name: 'Guard Pro Phone Case',
    category: 'Accessories',
    price: 449,
    oldPrice: 699,
    stock: 60,
    reorderLevel: 20,
    rating: 4.1,
    ratingCount: 1890,
    image: 'https://images.pexels.com/photos/7742552/pexels-photo-7742552.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Shock-absorbing phone case with raised camera bezel and a soft-touch matte finish.',
    specs: { Material: 'TPU + PC', Drop: '3m certified', Finish: 'Matte', Fit: 'Multiple models' },
    bestSeller: true,
    specialOffer: true,
  },
  {
    id: 'p26',
    name: 'Slim RFID Leather Wallet',
    category: 'Accessories',
    price: 999,
    stock: 24,
    reorderLevel: 10,
    rating: 4.5,
    ratingCount: 612,
    image: 'https://images.pexels.com/photos/4452399/pexels-photo-4452399.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Minimalist leather wallet with RFID blocking and 8 card slots in a slim profile.',
    specs: { Material: 'Genuine leather', Slots: '8 cards', 'RFID block': 'Yes', Dimensions: '11x9cm' },
    trending: true,
  },
  {
    id: 'p27',
    name: 'Bloom Silk Scarf',
    category: 'Fashion',
    price: 1299,
    oldPrice: 1799,
    stock: 9,
    reorderLevel: 8,
    rating: 4.4,
    ratingCount: 188,
    image: 'https://images.pexels.com/photos/36455709/pexels-photo-36455709.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    description: 'Lightweight silk scarf with a hand-rolled hem and an abstract botanical print.',
    specs: { Material: '100% silk', Size: '90x90cm', Print: 'Botanical', Care: 'Dry clean' },
    specialOffer: true,
  },
];

export const fallbackOrders: FallbackOrder[] = [
  {
    orderId: 'ORD-1001',
    customerName: 'Aarav Sharma',
    customerEmail: 'aarav@example.com',
    customerPhone: '98765 43210',
    address: '12 MG Road, Aarav Nagar',
    city: 'Bengaluru',
    pincode: '560001',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'p1',
        name: 'Aurora Wireless Over-Ear Headphones',
        price: 2499,
        quantity: 1,
        image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
      {
        productId: 'p8',
        name: 'ChargeUp 20000mAh Power Bank',
        price: 1299,
        quantity: 1,
        image: 'https://images.pexels.com/photos/4072683/pexels-photo-4072683.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
    ],
    totalAmount: 3798,
    orderDate: daysAgo(26),
    status: 'Delivered',
  },
  {
    orderId: 'ORD-1002',
    customerName: 'Priya Nair',
    customerEmail: 'priya@example.com',
    customerPhone: '98765 43210',
    address: '12 MG Road, Priya Nagar',
    city: 'Bengaluru',
    pincode: '560001',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'p11',
        name: 'Stride Runner Sneakers',
        price: 2199,
        quantity: 2,
        image: 'https://images.pexels.com/photos/1027130/pexels-photo-1027130.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
    ],
    totalAmount: 4398,
    orderDate: daysAgo(24),
    status: 'Delivered',
  },
  {
    orderId: 'ORD-1003',
    customerName: 'Rohan Mehta',
    customerEmail: 'rohan@example.com',
    customerPhone: '98765 43210',
    address: '12 MG Road, Rohan Nagar',
    city: 'Bengaluru',
    pincode: '560001',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'p5',
        name: 'Nimbus 14 Ultrabook Laptop',
        price: 54999,
        quantity: 1,
        image: 'https://images.pexels.com/photos/8533587/pexels-photo-8533587.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
    ],
    totalAmount: 54999,
    orderDate: daysAgo(21),
    status: 'Delivered',
  },
  {
    orderId: 'ORD-1004',
    customerName: 'Ananya Iyer',
    customerEmail: 'ananya@example.com',
    customerPhone: '98765 43210',
    address: '12 MG Road, Ananya Nagar',
    city: 'Bengaluru',
    pincode: '560001',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'p7',
        name: 'Boom 20 Portable Bluetooth Speaker',
        price: 1799,
        quantity: 1,
        image: 'https://images.pexels.com/photos/4917455/pexels-photo-4917455.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
      {
        productId: 'p2',
        name: 'Pulse True Wireless Earbuds',
        price: 1499,
        quantity: 1,
        image: 'https://images.pexels.com/photos/33797659/pexels-photo-33797659.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
    ],
    totalAmount: 3298,
    orderDate: daysAgo(19),
    status: 'Delivered',
  },
  {
    orderId: 'ORD-1005',
    customerName: 'Karthik Reddy',
    customerEmail: 'karthik@example.com',
    customerPhone: '98765 43210',
    address: '12 MG Road, Karthik Nagar',
    city: 'Bengaluru',
    pincode: '560001',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'p17',
        name: 'Amber Scented Candle Set',
        price: 699,
        quantity: 3,
        image: 'https://images.pexels.com/photos/13395697/pexels-photo-13395697.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
    ],
    totalAmount: 2097,
    orderDate: daysAgo(17),
    status: 'Delivered',
  },
  {
    orderId: 'ORD-1006',
    customerName: 'Sneha Pillai',
    customerEmail: 'sneha@example.com',
    customerPhone: '98765 43210',
    address: '12 MG Road, Sneha Nagar',
    city: 'Bengaluru',
    pincode: '560001',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'p14',
        name: 'Aviator Polarized Sunglasses',
        price: 899,
        quantity: 2,
        image: 'https://images.pexels.com/photos/8989491/pexels-photo-8989491.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
      {
        productId: 'p15',
        name: 'Heritage Leather Belt',
        price: 799,
        quantity: 1,
        image: 'https://images.pexels.com/photos/31959214/pexels-photo-31959214.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
    ],
    totalAmount: 2597,
    orderDate: daysAgo(14),
    status: 'Delivered',
  },
  {
    orderId: 'ORD-1007',
    customerName: 'Vikram Joshi',
    customerEmail: 'vikram@example.com',
    customerPhone: '98765 43210',
    address: '12 MG Road, Vikram Nagar',
    city: 'Bengaluru',
    pincode: '560001',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'p3',
        name: 'Vital Fit Smartwatch',
        price: 3299,
        quantity: 1,
        image: 'https://images.pexels.com/photos/18662969/pexels-photo-18662969.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
    ],
    totalAmount: 3299,
    orderDate: daysAgo(9),
    status: 'Shipped',
  },
  {
    orderId: 'ORD-1008',
    customerName: 'Meera Kapoor',
    customerEmail: 'meera@example.com',
    customerPhone: '98765 43210',
    address: '12 MG Road, Meera Nagar',
    city: 'Bengaluru',
    pincode: '560001',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'p24',
        name: 'Voyage Leather Backpack',
        price: 2799,
        quantity: 1,
        image: 'https://images.pexels.com/photos/14039946/pexels-photo-14039946.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
      {
        productId: 'p26',
        name: 'Slim RFID Leather Wallet',
        price: 999,
        quantity: 1,
        image: 'https://images.pexels.com/photos/4452399/pexels-photo-4452399.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
    ],
    totalAmount: 3798,
    orderDate: daysAgo(7),
    status: 'Shipped',
  },
  {
    orderId: 'ORD-1009',
    customerName: 'Arjun Das',
    customerEmail: 'arjun@example.com',
    customerPhone: '98765 43210',
    address: '12 MG Road, Arjun Nagar',
    city: 'Bengaluru',
    pincode: '560001',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'p9',
        name: 'Glide Wireless Mouse',
        price: 699,
        quantity: 2,
        image: 'https://images.pexels.com/photos/7151696/pexels-photo-7151696.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
    ],
    totalAmount: 1398,
    orderDate: daysAgo(4),
    status: 'Confirmed',
  },
  {
    orderId: 'ORD-1010',
    customerName: 'Ishaan Verma',
    customerEmail: 'ishaan@example.com',
    customerPhone: '98765 43210',
    address: '12 MG Road, Ishaan Nagar',
    city: 'Bengaluru',
    pincode: '560001',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'p20',
        name: 'Brew Drip Coffee Maker',
        price: 4299,
        quantity: 1,
        image: 'https://images.pexels.com/photos/12090814/pexels-photo-12090814.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
      {
        productId: 'p21',
        name: 'Halo LED Desk Lamp',
        price: 1499,
        quantity: 1,
        image: 'https://images.pexels.com/photos/28461166/pexels-photo-28461166.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
    ],
    totalAmount: 5798,
    orderDate: daysAgo(3),
    status: 'Confirmed',
  },
  {
    orderId: 'ORD-1011',
    customerName: 'Tara Singh',
    customerEmail: 'tara@example.com',
    customerPhone: '98765 43210',
    address: '12 MG Road, Tara Nagar',
    city: 'Bengaluru',
    pincode: '560001',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'p4',
        name: 'TrailCam 4K Action Camera',
        price: 8999,
        quantity: 1,
        image: 'https://images.pexels.com/photos/4817132/pexels-photo-4817132.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
    ],
    totalAmount: 8999,
    orderDate: daysAgo(1),
    status: 'Placed',
  },
  {
    orderId: 'ORD-1012',
    customerName: 'Nisha Gupta',
    customerEmail: 'nisha@example.com',
    customerPhone: '98765 43210',
    address: '12 MG Road, Nisha Nagar',
    city: 'Bengaluru',
    pincode: '560001',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'p13',
        name: 'Cozy Knit Sweater',
        price: 1299,
        quantity: 2,
        image: 'https://images.pexels.com/photos/14642651/pexels-photo-14642651.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
      {
        productId: 'p19',
        name: 'Cloudweave Throw Blanket',
        price: 1599,
        quantity: 1,
        image: 'https://images.pexels.com/photos/31658575/pexels-photo-31658575.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
    ],
    totalAmount: 4197,
    orderDate: daysAgo(1),
    status: 'Placed',
  },
  {
    orderId: 'ORD-1013',
    customerName: 'Aditya Rao',
    customerEmail: 'aditya@example.com',
    customerPhone: '98765 43210',
    address: '12 MG Road, Aditya Nagar',
    city: 'Bengaluru',
    pincode: '560001',
    paymentMethod: 'Cash on Delivery',
    items: [
      {
        productId: 'p10',
        name: 'Tactile 75 Mechanical Keyboard',
        price: 3299,
        quantity: 1,
        image: 'https://images.pexels.com/photos/9020272/pexels-photo-9020272.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      },
    ],
    totalAmount: 3299,
    orderDate: daysAgo(0),
    status: 'Placed',
  },
];
